name: egms-ortho
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.13
  - numpy>=1.26
  - pandas>=2.1
  - geopandas>=0.14
  - pyproj>=3.6
  - shapely>=2.0
  - fiona>=1.9
  - rasterio>=1.3
  - pyarrow>=15.0
  - dask>=2024.5
  - distributed>=2024.5
  - fsspec>=2024.3
  - dask-labextension>=7.0
  - jupyterlab>=4.0
